// <auto-generated />
using System;
using LieferHero.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LieferHero.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240711215300_InitialMig")]
    partial class InitialMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("LieferHero.Models.Bestellung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BestellZeit")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bestellungen");
                });

            modelBuilder.Entity("LieferHero.Models.BestellungAufgeben", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GesamtKosten")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nachricht")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AufgegebeneBesellungen");
                });

            modelBuilder.Entity("LieferHero.Models.Speise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Speisen");
                });

            modelBuilder.Entity("LieferHero.Models.SpeiseHinzufuegenAnfrage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Menge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpeiseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SpeiseHinzufuegenAnfragen");
                });

            modelBuilder.Entity("LieferHero.Models.SpeiseInBestellung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BestellungId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Menge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpeiseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BestellungId");

                    b.HasIndex("SpeiseId");

                    b.ToTable("SpeisenInBestellung");
                });

            modelBuilder.Entity("LieferHero.Models.SpeiseInBestellung", b =>
                {
                    b.HasOne("LieferHero.Models.Bestellung", null)
                        .WithMany("Speisen")
                        .HasForeignKey("BestellungId");

                    b.HasOne("LieferHero.Models.Speise", "Speise")
                        .WithMany()
                        .HasForeignKey("SpeiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Speise");
                });

            modelBuilder.Entity("LieferHero.Models.Bestellung", b =>
                {
                    b.Navigation("Speisen");
                });
#pragma warning restore 612, 618
        }
    }
}
